[project]
name = "comfaq"
version = "0.1.0"
description = "Warhammer: the old world, community FAQ"
readme = "README.md"
authors = [
    { name = "nicolas carrara", email = "nicolas.carrara1u@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "jinja2>=3.1.6",
    "markdown-it-py>=3.0.0",
    "pydantic>=2.12.0",
    "python-frontmatter>=1.1.0",
    "typer>=0.16.0",
    "weasyprint>=65.0",
]

[project.scripts]
comfaq = "comfaq.cli:app"

[build-system]
requires = ["uv_build>=0.9.0,<0.11.0"]
build-backend = "uv_build"
